language: python

python:
  - "2.7"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh							 
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy gsl pytest
  - python setup.py build_ext --inplace
  - python setup.py build
  - python setup.py install

script:
  # pytest
  - pytest
  # script docs
  - MGSIM -h