version: 2.1
jobs:
  build-and-test:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON_VERSION: 3.6
    steps:
      - checkout
      - run:
          name: conda env setup
          command: |
            conda install -c conda-forge --yes mamba
            mamba create -n test_env -c conda-forge -c bioconda python=$PYTHON_VERSION numpy pandas docopt configobj scipy biopython art pyfasta pyfastx pytest pytest-console-scripts
      - run:
          name: pytest
          command: |
            conda init bash
            source ~/.bashrc
            conda activate test_env
            conda list
            pytest -s
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test